http://localhost:3000

###
POST http://localhost:3000/api/signup
Content-Type: application/json


{
    "name": "John Doe",
    "email": "john.doe22@example.com",
    "password": "this73838101@securedBig",
    "confirm_password": "this73838101@securedBig"
}

###
POST http://localhost:3000/api/signin
Content-Type: application/json


{
    "email": "john.doe22@example.com",
    "password": "this73838101@securedBig"
}


### 
POST http://localhost:3000/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsImVtYWlsIjoiam9obi5kb2UyMkBleGFtcGxlLmNvbSIsImlhdCI6MTc4NDMxMTM1MCwiZXhwIjoxNzg0MzE0OTUwfQ.b60F6RNoIM6p1GrZ6HAFIxXKwKWoTINQSnKpyHdS_fc

{
    "title": "My First Note",
    "content": "This is the content of my first note."
}

###
GET http://localhost:3000/api/notes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsImVtYWlsIjoiam9obi5kb2UyMkBleGFtcGxlLmNvbSIsImlhdCI6MTc4NDMxMTM1MCwiZXhwIjoxNzg0MzE0OTUwfQ.b60F6RNoIM6p1GrZ6HAFIxXKwKWoTINQSnKpyHdS_fc

###
PATCH http://localhost:3000/api/notes/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsImVtYWlsIjoiam9obi5kb2UyMkBleGFtcGxlLmNvbSIsImlhdCI6MTc4NDMxMTM1MCwiZXhwIjoxNzg0MzE0OTUwfQ.b60F6RNoIM6p1GrZ6HAFIxXKwKWoTINQSnKpyHdS_fc

{
    "title": "Updated Note Title",
    "content": "This is the updated content of my note."
}


### 
DELETE http://localhost:3000/api/notes/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsImVtYWlsIjoiam9obi5kb2UyMkBleGFtcGxlLmNvbSIsImlhdCI6MTc4NDMxMTM1MCwiZXhwIjoxNzg0MzE0OTUwfQ.b60F6RNoIM6p1GrZ6HAFIxXKwKWoTINQSnKpyHdS_fc



